### ISSUE TITLE
removing the String#== override

### ISSUE THREAD

**Issue by codekitchen** [aq1018/active_model-better_errors#1]
Hi, we're evaluating using active_model-better_errors in our Rails application, it looks to be just what we need for getting our API error responses under control. We have a policy of avoiding gems that override methods in core ruby classes, though, when at all possible (rails itself being the big exception here of course). The override of `String#==` in the gem at https://github.com/aq1018/active_model-better_errors/blob/master/lib/active_model/error_collecting/core_ext.rb seems to be mostly only useful in tests, is it something you'd consider removing? I can send up a pull request, if so. Thanks.

**Comment by krainboltgreene** [comment]
That's not a terrible idea. Maybe just move it to the spec helper. I don't think @aq1018 would mind.

**Comment by codekitchen** [comment]
pull request #2 filed

**Comment by codekitchen** [comment]
thanks for the quick response!
