### ISSUE TITLE
breaks when using autosave mode

### ISSUE THREAD

**Issue by aserafin** [aq1018/active_model-better_errors#13]
Consider this code

```
class Foo
  has_many :bars, autosave: true
end
```

`bars` are validated with special `AssociationValidator` that will copy errors from `bars` to the parent `Foo` object and this breaks `HumanMessageFormatter` `value` method.

I don't really care about error messages from `Bar` in `Foo` so I've just overriden `AssociationValidator` class in my project to not put them there.

Another solution would be to `rescue nil` in this method

```
  def value
    return if attribute == :base
    base.send :read_attribute_for_validation, attribute rescue nil
  end
```

in `HumanMessageFormatter` but it's not the most elegant way. 

BTW. awesome library, huge improvement from standard activemodel errors :)

**Comment by aq1018** [comment]
I'll try reproduce this with a spec first, then I'll see what's the best way to fix this

**Comment by aq1018** [comment]
This `ActiveRecord` specific, since `ActiveModel` seem to handle this differently. I need to dig into `ActiveRecord` to see how they are integrated.

**Comment by aq1018** [comment]
v1.6.6 released
