### ISSUE TITLE
Switch to new rspec syntax

### ISSUE THREAD

**Issue by krainboltgreene** [aq1018/active_model-better_errors#4]
`expect()` and `allow()`. I'll hit on this tonight or tomorrow.

**Comment by aq1018** [comment]
Sounds good. :+1:  Add yourself to the authors list if you want?

**Comment by aq1018** [comment]
@krainboltgreene Just in case if you are working on this. I've updated the gem builder from `jeweler` to `bundler` since jeweler is already very outdated. You might want to rebase.

**Comment by krainboltgreene** [comment]
Got it thanks, that's another thing I was going to do.

On Mon, Dec 9, 2013 at 4:31 PM, Aaron Qian notifications@github.com wrote:

> @krainboltgreene https://github.com/krainboltgreene Just in case if you
> are working on this. I've updated the gem builder from jeweler to
> 'bundler` since jeweler is already very outdated. You might want to rebase.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aq1018/active_model-better_errors/issues/4#issuecomment-30189084
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017

**Comment by aq1018** [comment]
Seems you are getting close, you want to send a PR and move the discussions there?

**Comment by aq1018** [comment]
I saw you using rubocop in your branch. This is awesome. But I'd like to go a step further using [devtools](https://github.com/rom-rb/devtools). Please take a look at [my branch](https://github.com/aq1018/active_model-better_errors/tree/devtools) I think we are doing more or less the same things. Maybe we should work on this together?

**Comment by aq1018** [comment]
Alright... I merged in devtools branch already, and fixed all the rubocop errors. But `README.md` changes and `should -> expect` changes are still valuable. Do you want to merge?

**Comment by krainboltgreene** [comment]
I didn't end up liking devtools, but I see no reason to only do rubocop for this library. I'll rebase after we get the new relase out.

**Comment by aq1018** [comment]
Any reasons why you don't like devtools? I'd like to hear your input on this. Also the new release is a pretty significant change. I guess I'll change the specs to new syntax along the way.
