### ISSUE TITLE
pluggable HumanMessageFormatter

### ISSUE THREAD

**Issue by codekitchen** [aq1018/active_model-better_errors#5]
We'd like to replace a lot of the logic in HumanMessageFormatter in some cases, because our API error messages don't use the I18n library. One option I see is to add another reporter, :message_formatter, and then allow overrides with `ActiveModel::ErrorCollecting.set_reporter(:message_formatter, MyFormatterClass)`. But that seems slightly hokey just because it's not quite a "reporter" in the sense that the others are. What do you think?

**Comment by krainboltgreene** [comment]
I definitely see the value here, and probably the best place for dependency injection. We shouldn't care what kind of object you give us, as long as it responds to the "formatter" spec.

**Comment by aq1018** [comment]
Please discuss this on #6 . Closing this one.
